// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvgwajegdhqjmhqkkgwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Z3dhamVnZGhxam1ocWtrZ3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTI0OTgsImV4cCI6MjA3NDM4ODQ5OH0.1hHW-FeMXY4hu7Aq-oqr9bzC6mPnuR-Bpuf3ZJ6LsfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});